language: node_js
node_js:
    - 9
before_install:
  - npm i -g npm@latest
install:
    - npm ci
script:
    - npm run test
sudo: required
notifications:
  email: false
deploy:
  provider: npm
  email: michal@fabulator.cz
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
